In [1]:
import random
import numpy as np
from IPython.display import display, clear_output

In [2]:
class Jogo8Puzzle:
    def __init__(self):
        self.estado_objetivo = np.array([
                                [1, 2, 3],
                                [4, 5, 6],
                                [7, 8, 0]
                            ])
        
        self.estado_atual = self.estado_objetivo.copy()
        self.embaralhar()

    def embaralhar(self):
        for _ in range(3):
            self.mover_aleatorio()

    def mover_aleatorio(self):
        movimentos_possiveis = self.obter_movimentos_possiveis()
        if movimentos_possiveis:
            # movimento = [ tupla(linha, coluna), direcao ]
            # movimento[0] = tupla(linha, coluna)
            movimento = random.choice(movimentos_possiveis)
            self.mover(movimento[0])

    def obter_movimentos_possiveis(self):
        linha_vazia, coluna_vazia = np.where(self.estado_atual == 0)
        # np.where -> tupla (linha, coluna)
        movimentos_possiveis = []
        # tupla(linha, coluna), direcao

        # w -> cima, s -> baixo, a -> esquerda, d -> direita
        # [2],[2]
        if linha_vazia > 0:
            movimentos_possiveis.append((
                (linha_vazia - 1, coluna_vazia), 'w'
            ))

        if linha_vazia < 2:
            movimentos_possiveis.append((
                (linha_vazia + 1, coluna_vazia), 's'
            ))

        if coluna_vazia > 0:
            movimentos_possiveis.append((
                (linha_vazia, coluna_vazia - 1), 'a'
            ))
        
        if coluna_vazia < 2:
            movimentos_possiveis.append((
                (linha_vazia, coluna_vazia + 1), 'd'
            ))

        return movimentos_possiveis  

    def mover(self, posicao):
        linha_vazia, coluna_vazia = np.where(self.estado_atual == 0)
        nova_linha, nova_coluna = posicao

        self.estado_atual[linha_vazia, coluna_vazia], self.estado_atual[nova_linha, nova_coluna] = \
            self.estado_atual[nova_linha, nova_coluna], self.estado_atual[linha_vazia, coluna_vazia]
    
    def mostrar_tabuleiro(self):
        print(self.estado_atual)

    def jogar(self):
        jogo_ativo = True
        while jogo_ativo:
            clear_output(wait=True)
            self.mostrar_tabuleiro()
            print("Use as teclas w, s, a, d para mover o espaço vazio")

            movimentos_possiveis = self.obter_movimentos_possiveis()
            print("Movimentos possíveis:")
            for movimento in movimentos_possiveis:
                posicao, direcao = movimento
                linha, coluna = posicao
                peca = self.estado_atual[linha, coluna]
                print(f"{direcao}: Mover peça {peca}. Posição {linha}, {coluna}")
            movimento = input("Digite o movimento: ").lower()

            if movimento == 'q':
                jogo_ativo = False
                print("Jogo encerrado")
                break
            elif movimento in ['w', 'a', 's', 'd']:
                # Filtra movimentos válidos
                movimentos_validos = []
                # Se o movimento for igual ao movimento informado, adiciona na lista
                for mov in movimentos_possiveis:
                    direcao = mov[1]
                    movimentos_validos.append(direcao)

                if movimento in movimentos_validos:
                    for movimento_possivel in movimentos_possiveis:
                        if movimento_possivel[1] == movimento:
                            posicao = movimento_possivel[0]
                            self.mover(posicao)
                            break
            else:
                print("Movimento inválido")

            if np.array_equal(self.estado_atual, self.estado_objetivo):
                clear_output(wait=True)
                self.mostrar_tabuleiro()
                print("Parabéns, você venceu!")
                jogo_ativo = False
            

In [3]:
jogo = Jogo8Puzzle()
jogo.jogar()

[[1 2 3]
 [4 5 6]
 [7 0 8]]
Use as teclas w, s, a, d para mover o espaço vazio
Movimentos possíveis:
w: Mover peça [5]. Posição [1], [1]
a: Mover peça [7]. Posição [2], [0]
d: Mover peça [8]. Posição [2], [2]
Jogo encerrado


Atividade Aula 02 - Algoritmo BFS

In [4]:
import numpy as np

def estado_para_string(estado):
    return ''.join(str(i) for i in estado.flatten())

def busca_em_largura(estado_inicial):
    fila = []
    fila.append([estado_inicial.estado_atual, []])
    tamanho_busca = 0

    visitados = set()
    visitados.add(estado_para_string(estado_inicial.estado_atual))
    while fila:
        estado, caminho = fila.pop(0)

        jogo_while = Jogo8Puzzle()
        jogo_while.estado_atual = np.array(estado)

        if np.array_equal(jogo_while.estado_atual, jogo_while.estado_objetivo):
            return (caminho, tamanho_busca)
        else:
            tamanho_busca += 1
        
        movimentos_possiveis = jogo_while.obter_movimentos_possiveis()

        if movimentos_possiveis:
            for posicao, direcao in movimentos_possiveis:             

                jogo_for = Jogo8Puzzle()
                jogo_for.estado_atual = jogo_while.estado_atual.copy()
                jogo_for.mover(posicao)                              

                if estado_para_string(jogo_for.estado_atual) in visitados:
                    continue
                else:
                    atualiza_caminho = caminho[:]
                    atualiza_caminho.append(direcao)
                    #print(posicao, direcao, "\n", jogo_for.estado_atual)

                    visitados.add(estado_para_string(jogo_for.estado_atual))
                    fila.append([jogo_for.estado_atual, atualiza_caminho])
    
    return None

# Crie uma instância da classe Jogo8Puzzle com o estado inicial desejado
jogo = Jogo8Puzzle()
'''
jogo.estado_atual = np.array([[4, 1, 3],
                              [7, 6, 0],
                              [5, 2, 8]])

'''
jogo.estado_atual = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 0, 8]])


# Execute o algoritmo BFS para encontrar a sequência de jogadas que resolvem o problema
sequencia_jogadas, tamanho_busca = busca_em_largura(jogo)

# Exiba a sequência de jogadas
if sequencia_jogadas:
    print("Sequência de jogadas para resolver o problema:")
    print(jogo.estado_atual)
    
    for direcao in sequencia_jogadas:
        print(f"Mover para a direção {direcao}")
        
    print(sequencia_jogadas)
    print(f"Jogo resolvido em {len(sequencia_jogadas)} jogada(s), com busca em {tamanho_busca} estados.")
else:
    print("Não foi possível encontrar uma solução.")  
    

    
    
    
    

Sequência de jogadas para resolver o problema:
[[1 2 3]
 [4 5 6]
 [7 0 8]]
Mover para a direção d
['d']
Jogo resolvido em 1 jogada(s), com busca em 3 estados.


Algoritmo de Busca em Profundidade

In [9]:
import numpy as np

def estado_para_string(estado):
    return ''.join(str(i) for i in estado.flatten())

def busca_em_profundidade(estado_atual, caminho_atual, visitados, max_profundidade):
    if estado_para_string(estado_atual) in visitados:
        return None

    visitados.add(estado_para_string(estado_atual))

    if np.array_equal(estado_atual, jogo.estado_objetivo):
        return caminho_atual

    if max_profundidade == 0:
        return None

    movimentos_possiveis = obter_movimentos_possiveis(estado_atual)

    for posicao, direcao in movimentos_possiveis:
        novo_estado = estado_atual.copy()
        mover(novo_estado, posicao)

        novo_caminho = caminho_atual[:]
        novo_caminho.append(direcao)

        resultado = busca_em_profundidade(novo_estado, novo_caminho, visitados, max_profundidade - 1)
        if resultado is not None:
            return resultado
    
    return None

def obter_movimentos_possiveis(estado):
    linha_vazia, coluna_vazia = np.where(estado == 0)
    movimentos_possiveis = []

    if linha_vazia > 0:
        movimentos_possiveis.append(((linha_vazia - 1, coluna_vazia), 'w'))

    if linha_vazia < 2:
        movimentos_possiveis.append(((linha_vazia + 1, coluna_vazia), 's'))

    if coluna_vazia > 0:
        movimentos_possiveis.append(((linha_vazia, coluna_vazia - 1), 'a'))
    
    if coluna_vazia < 2:
        movimentos_possiveis.append(((linha_vazia, coluna_vazia + 1), 'd'))

    return movimentos_possiveis

def mover(estado, posicao):
    linha_vazia, coluna_vazia = np.where(estado == 0)
    nova_linha, nova_coluna = posicao
    estado[linha_vazia, coluna_vazia], estado[nova_linha, nova_coluna] = estado[nova_linha, nova_coluna], estado[linha_vazia, coluna_vazia]


# Criação do jogo
jogo = Jogo8Puzzle()

# Definir estado inicial desejado aqui
estado_inicial_desejado = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
])

# Chamar a busca em profundidade
sequencia_jogadas = busca_em_profundidade(jogo.estado_atual, [], set(), max_profundidade=15)

if sequencia_jogadas:
    print("Sequência de jogadas para resolver o problema:")
    print(jogo.estado_atual)
    
    for direcao in sequencia_jogadas:
        print(f"Mover para a direção {direcao}")
        
    print(sequencia_jogadas)
    print(f"Jogo resolvido em {len(sequencia_jogadas)} jogada(s).")
else:
    print("Solução não encontrada dentro da profundidade máxima.")
    


Sequência de jogadas para resolver o problema:
[[1 0 2]
 [4 5 3]
 [7 8 6]]
Mover para a direção s
Mover para a direção a
Mover para a direção s
Mover para a direção d
Mover para a direção w
Mover para a direção w
Mover para a direção d
Mover para a direção s
Mover para a direção a
Mover para a direção s
Mover para a direção a
Mover para a direção w
Mover para a direção d
Mover para a direção d
Mover para a direção s
['s', 'a', 's', 'd', 'w', 'w', 'd', 's', 'a', 's', 'a', 'w', 'd', 'd', 's']
Jogo resolvido em 15 jogada(s).


'\nsequencia_jogadas, tamanho_busca = busca_em_largura(jogo)\n\n# Exiba a sequência de jogadas\nif sequencia_jogadas:\n    print("Sequência de jogadas para resolver o problema:")\n    print(jogo.estado_atual)\n    \n    for direcao in sequencia_jogadas:\n        print(f"Mover para a direção {direcao}")\n        \n    print(sequencia_jogadas)\n    print(f"Jogo resolvido em {len(sequencia_jogadas)} jogada(s), com busca em {tamanho_busca} estados.")\nelse:\n    print("Não foi possível encontrar uma solução.") \n\nResposta:\n\ncaminho_solucao = busca_em_profundidade(jogo.estado_atual, [], set(), max_profundidade=15)\n\nif caminho_solucao is not None:\n    print("Caminho até a solução:", caminho_solucao)\nelse:\n    print("Solução não encontrada dentro da profundidade máxima.")\n'